services:
  azure-ai-chat-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure-ai-foundry-chat-ui
    ports:
      - "8080:8080"
    environment:
      # これらの環境変数は実際の値に置き換えてください
      - VITE_AZURE_AI_FOUNDARY_ENDPOINT_URL=${VITE_AZURE_AI_FOUNDARY_ENDPOINT_URL}
      - VITE_AZURE_AI_FOUNDARY_API_KEY=${VITE_AZURE_AI_FOUNDARY_API_KEY}
      - VITE_AZURE_AI_AGENT_ID=${VITE_AZURE_AI_AGENT_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.azure-ai-chat.rule=Host(`localhost`)"
      - "traefik.http.services.azure-ai-chat.loadbalancer.server.port=8080"
    networks:
      - azure-ai-network

networks:
  azure-ai-network:
    driver: bridge
